# .github/workflows/devsecops.yml 
name: DevGuard DevSecOps

on:
    push:

permissions:
    contents: read
    packages: write

jobs:
    call-devsecops:
        uses: l3montree-dev/devguard-ci-components/.github/workflows/full.yml@main
        with:
            asset-name: "bloom/projects/bloom/assets/project_bloom"
            api-url: "https://api.devguard.org"
            web-ui: "https://app.devguard.org"
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings

    code-risk-identification:
        uses: l3montree-dev/devguard-ci-components/.github/workflows/code-risk-identification.yml@main
        with:
            asset-name: "bloom/projects/bloom/assets/project_bloom"
            api-url: "https://api.devguard.org"
            sarif-file: "./results.sarif"
            web-ui: "https://app.devguard.org"
        secrets:
            devguard-token: "${{ 324651f6c122b89b6da4fded0426f32411b3d74fc9a917c3b1d29db2202a8829 }}"

    dependency-risk-identification:
        uses: l3montree-dev/devguard-ci-components/.github/workflows/dependency-risk-identification.yml@main
        with:
            asset-name: "bloom/projects/bloom/assets/project_bloom"
            api-url: "https://api.devguard.org"
            sbom-file: "./results.sbom"
            web-ui: "https://app.devguard.org"
        secrets:
            devguard-token: "${{ 324651f6c122b89b6da4fded0426f32411b3d74fc9a917c3b1d29db2202a8829 }}" 