export type WeeklyData = {
  week: number;
  babyEmoji: string;
  babySizeAnalogy: string;
  length: string;
  weight: string;
  babyDev: string;
  bodyChanges: string;
};

export const WEEKLY_DATA: WeeklyData[] = [
  { week: 1, babyEmoji: '🌐', babySizeAnalogy: 'Microscopic Blastocyst', length: '0 cm', weight: '0 g', babyDev: 'Your baby is just a glimmer in your eye! This week is actually your period, but it counts as week 1 of your pregnancy cycle.', bodyChanges: 'You are not actually pregnant yet. Your body is preparing for ovulation.' },
  { week: 2, babyEmoji: '🧬', babySizeAnalogy: 'Fertilized Egg', length: '0 cm', weight: '0 g', babyDev: 'Ovulation occurs. If sperm meets egg, fertilization happens!', bodyChanges: 'Your uterine lining is thickening to prepare for a potential fertilized egg.' },
  { week: 3, babyEmoji: '🌱', babySizeAnalogy: 'Tiny Embryo', length: '0.1 cm', weight: '0 g', babyDev: 'The fertilized egg (blastocyst) implants into your uterine lining. The amniotic sac and placenta are beginning to form.', bodyChanges: 'You might experience very light spotting (implantation bleeding) or early signs like breast tenderness.' },
  { week: 4, babyEmoji: '🌾', babySizeAnalogy: 'Poppy Seed', length: '0.2 cm', weight: '0 g', babyDev: 'The embryo is dividing rapidly. The neural tube (which becomes the brain and spinal cord) is forming.', bodyChanges: 'You might miss your period. A home pregnancy test can usually detect hCG hormones now!' },
  { week: 5, babyEmoji: '🫘', babySizeAnalogy: 'Sesame Seed', length: '0.3 cm', weight: '0 g', babyDev: 'Your baby\'s heart begins to beat! Major organs like the kidneys, liver, and intestines are starting to take shape.', bodyChanges: 'Pregnancy hormones are surging. You might start feeling fatigued, nauseous, or needing to pee more often.' },
  { week: 6, babyEmoji: '🟢', babySizeAnalogy: 'Sweet Pea', length: '0.6 cm', weight: '0 g', babyDev: 'Tiny buds that will become arms and legs are forming. The jaw, cheeks, and chin are taking shape.', bodyChanges: 'Morning sickness might kick in. Your breasts may feel heavy and tender.' },
  { week: 7, babyEmoji: '🫐', babySizeAnalogy: 'Blueberry', length: '1.3 cm', weight: '0 g', babyDev: 'Your baby is generating new brain cells at a rate of 100 per minute! Kidneys are ready to start producing urine.', bodyChanges: 'You might notice food aversions or cravings. Your blood volume is increasing.' },
  { week: 8, babyEmoji: '🍓', babySizeAnalogy: 'Raspberry', length: '1.6 cm', weight: '1 g', babyDev: 'Fingers and toes are forming (though they are webbed). The taste buds are developing.', bodyChanges: 'Your uterus has doubled in size. You might feel more tired than usual.' },
  { week: 9, babyEmoji: '🫒', babySizeAnalogy: 'Green Olive', length: '2.3 cm', weight: '2 g', babyDev: 'Your baby has graduated from an embryo to a fetus! The heart is fully formed with four chambers.', bodyChanges: 'Hormonal shifts might cause mood swings. You might also notice slight bloating.' },
  { week: 10, babyEmoji: '🍒', babySizeAnalogy: 'Prune', length: '3.1 cm', weight: '4 g', babyDev: 'Bones and cartilage are forming. Vital organs are beginning to function together.', bodyChanges: 'The pregnancy hormone hCG is peaking, which means nausea might be at its worst, but relief is coming soon.' },
  { week: 11, babyEmoji: '🌰', babySizeAnalogy: 'Fig', length: '4.1 cm', weight: '7 g', babyDev: 'Your baby is kicking and stretching, though you can\'t feel it yet. Tooth buds are forming under the gums.', bodyChanges: 'Your hair and nails might be growing faster. Nausea might start to subside.' },
  { week: 12, babyEmoji: '🥝', babySizeAnalogy: 'Lime', length: '5.4 cm', weight: '14 g', babyDev: 'Reflexes are developing! Your baby can open and close their fingers and curl their toes.', bodyChanges: 'Your uterus is shifting upward, which might relieve some pressure on your bladder.' },
  { week: 13, babyEmoji: '🍑', babySizeAnalogy: 'Plum', length: '7.4 cm', weight: '23 g', babyDev: 'Vocal cords are forming. Your baby\'s intestines are moving from the umbilical cord into their abdomen.', bodyChanges: 'Welcome to the second trimester! Energy levels often return, and the risk of miscarriage drops significantly.' },
  { week: 14, babyEmoji: '🍋', babySizeAnalogy: 'Lemon', length: '8.7 cm', weight: '43 g', babyDev: 'Your baby can squint, frown, and grimace. They are starting to practice swallowing.', bodyChanges: 'You might start showing a tiny bump. Your appetite may return with a vengeance.' },
  { week: 15, babyEmoji: '🍎', babySizeAnalogy: 'Apple', length: '10.1 cm', weight: '70 g', babyDev: 'Your baby\'s hearing is developing. They might be able to hear your heartbeat and muffled outside noises.', bodyChanges: 'You might experience round ligament pain (sharp aches in your lower belly) as your uterus stretches.' },
  { week: 16, babyEmoji: '🥑', babySizeAnalogy: 'Avocado', length: '11.6 cm', weight: '100 g', babyDev: 'The nervous system is functioning. Your baby\'s eyes can perceive light, even though they are closed.', bodyChanges: 'You might feel the first flutters of movement, known as "quickening," though it\'s normal if you don\'t yet.' },
  { week: 17, babyEmoji: '🍐', babySizeAnalogy: 'Pear', length: '13 cm', weight: '140 g', babyDev: 'Your baby\'s skeleton is changing from soft cartilage to bone. The umbilical cord is growing thicker and stronger.', bodyChanges: 'Your center of gravity is shifting. You might notice changes in your balance.' },
  { week: 18, babyEmoji: '🍠', babySizeAnalogy: 'Sweet Potato', length: '14.2 cm', weight: '190 g', babyDev: 'Your baby is yawning and hiccuping. A protective coating called myelin is forming around their nerves.', bodyChanges: 'If you haven\'t felt movement yet, you likely will soon! You might also experience mild swelling in your feet.' },
  { week: 19, babyEmoji: '🥭', babySizeAnalogy: 'Mango', length: '15.3 cm', weight: '240 g', babyDev: 'A waxy coating called vernix caseosa is forming on your baby\'s skin to protect it from the amniotic fluid.', bodyChanges: 'You might experience leg cramps, especially at night. Staying hydrated can help.' },
  { week: 20, babyEmoji: '🍌', babySizeAnalogy: 'Banana', length: '16.4 cm', weight: '300 g', babyDev: 'You are halfway there! Your baby is swallowing more and producing meconium (their first poop).', bodyChanges: 'Your uterus is at the level of your belly button. Your hair might look thicker and shinier.' },
  { week: 21, babyEmoji: '🥕', babySizeAnalogy: 'Carrot', length: '26.7 cm', weight: '360 g', babyDev: 'Your baby\'s taste buds are working! They can taste the flavors of what you eat through the amniotic fluid.', bodyChanges: 'You might notice stretch marks appearing. Your baby\'s movements are becoming stronger.' },
  { week: 22, babyEmoji: '🫑', babySizeAnalogy: 'Bell Pepper', length: '27.8 cm', weight: '430 g', babyDev: 'Your baby looks like a miniature newborn. Their lips, eyelids, and eyebrows are becoming more distinct.', bodyChanges: 'You might experience Braxton Hicks contractions (painless practice contractions).' },
  { week: 23, babyEmoji: '🌽', babySizeAnalogy: 'Ear of Corn', length: '28.9 cm', weight: '500 g', babyDev: 'Your baby\'s lungs are developing rapidly, preparing for breathing air. They are also starting to dream!', bodyChanges: 'You might notice a dark line down your belly called the linea nigra. Swelling in your ankles is common.' },
  { week: 24, babyEmoji: '🍆', babySizeAnalogy: 'Eggplant', length: '30 cm', weight: '600 g', babyDev: 'Your baby\'s inner ear is fully developed, meaning they can tell if they are upside down or right side up.', bodyChanges: 'Your eyes might feel dry or sensitive to light. You will likely have your glucose screening test soon.' },
  { week: 25, babyEmoji: '🥒', babySizeAnalogy: 'Cucumber', length: '34.6 cm', weight: '660 g', babyDev: 'Your baby\'s skin is smoothing out as they gain baby fat. Their hair is growing and developing color and texture.', bodyChanges: 'You might experience heartburn or indigestion as your growing uterus pushes against your stomach.' },
  { week: 26, babyEmoji: '🧅', babySizeAnalogy: 'Red Onion', length: '35.6 cm', weight: '760 g', babyDev: 'Your baby\'s eyes are opening! They are starting to blink and respond to light.', bodyChanges: 'Your blood pressure might increase slightly. You might also notice clumsiness due to loosened joints.' },
  { week: 27, babyEmoji: '🥦', babySizeAnalogy: 'Broccoli Head', length: '36.6 cm', weight: '875 g', babyDev: 'Your baby is practicing breathing by inhaling and flexing amniotic fluid. Their brain is very active.', bodyChanges: 'Welcome to the third trimester! You might feel more fatigued again and experience shortness of breath.' },
  { week: 28, babyEmoji: '🥬', babySizeAnalogy: 'Romaine Lettuce', length: '37.6 cm', weight: '1 kg', babyDev: 'Your baby\'s heartbeat can now be heard through a stethoscope. They are dreaming and having REM sleep.', bodyChanges: 'You might experience sciatica (nerve pain in your lower back and legs). Your breasts might leak colostrum.' },
  { week: 29, babyEmoji: '🍈', babySizeAnalogy: 'Cantaloupe', length: '38.6 cm', weight: '1.2 kg', babyDev: 'Your baby\'s muscles and lungs are continuing to mature. Their head is growing to accommodate their developing brain.', bodyChanges: 'You might need to pee more often again as the baby presses on your bladder. Sleep might be getting uncomfortable.' },
  { week: 30, babyEmoji: '🍍', babySizeAnalogy: 'Pineapple', length: '39.9 cm', weight: '1.3 kg', babyDev: 'Your baby\'s vision is continuing to develop. They are surrounded by a pint and a half of amniotic fluid.', bodyChanges: 'You might experience mood swings again. Heartburn and indigestion might be more frequent.' },
  { week: 31, babyEmoji: '🥥', babySizeAnalogy: 'Coconut', length: '41.1 cm', weight: '1.5 kg', babyDev: 'Your baby is turning their head from side to side. A layer of fat is accumulating under their skin.', bodyChanges: 'You might notice your breasts getting larger and heavier. Braxton Hicks contractions might become more noticeable.' },
  { week: 32, babyEmoji: '🧸', babySizeAnalogy: 'Teddy Bear', length: '42.4 cm', weight: '1.7 kg', babyDev: 'Your baby is taking up most of the space in your uterus. Their toenails and fingernails are fully formed.', bodyChanges: 'You might experience lower back pain. Your blood volume is 40-50% higher than before you were pregnant.' },
  { week: 33, babyEmoji: '🥖', babySizeAnalogy: 'Loaf of Bread', length: '43.7 cm', weight: '1.9 kg', babyDev: 'Your baby\'s immune system is developing as they receive antibodies from you. Their bones are hardening.', bodyChanges: 'You might feel clumsy or off-balance. Insomnia is common as it gets harder to find a comfortable sleeping position.' },
  { week: 34, babyEmoji: '🍉', babySizeAnalogy: 'Watermelon', length: '45 cm', weight: '2.1 kg', babyDev: 'Your baby\'s lungs are almost fully mature. They are likely settling into a head-down position for birth.', bodyChanges: 'You might experience pelvic pressure as the baby drops lower. Your vision might be slightly blurry due to hormones.' },
  { week: 35, babyEmoji: '⚽', babySizeAnalogy: 'Soccer Ball', length: '46.2 cm', weight: '2.4 kg', babyDev: 'Your baby\'s kidneys are fully developed, and their liver can process some waste products.', bodyChanges: 'You might feel frequent urges to urinate. You might also notice an increase in vaginal discharge.' },
  { week: 36, babyEmoji: '🎒', babySizeAnalogy: 'School Backpack', length: '47.4 cm', weight: '2.6 kg', babyDev: 'Your baby is shedding the downy hair (lanugo) and the waxy coating (vernix) that protected them.', bodyChanges: 'Your baby might "drop" into your pelvis, making it easier to breathe but increasing pelvic pressure.' },
  { week: 37, babyEmoji: '🎃', babySizeAnalogy: 'Large Pumpkin', length: '48.6 cm', weight: '2.9 kg', babyDev: 'Your baby is considered "early term." They are practicing breathing, sucking, and swallowing.', bodyChanges: 'You might lose your mucus plug. Braxton Hicks contractions might feel stronger and more frequent.' },
  { week: 38, babyEmoji: '🪆', babySizeAnalogy: 'Nesting Doll', length: '49.8 cm', weight: '3.1 kg', babyDev: 'Your baby\'s brain and lungs are still maturing, but they are ready for life outside the womb. They have a firm grasp.', bodyChanges: 'You might feel anxious or excited. Swelling in your feet and ankles might be more pronounced.' },
  { week: 39, babyEmoji: '📦', babySizeAnalogy: 'Storage Box', length: '50.7 cm', weight: '3.3 kg', babyDev: 'Your baby is full term! They are continuing to build fat stores to help regulate their body temperature after birth.', bodyChanges: 'Your cervix might be dilating and effacing (thinning) in preparation for labor. Keep an eye out for signs of labor.' },
  { week: 40, babyEmoji: '👶', babySizeAnalogy: 'Newborn Baby', length: '51.2 cm', weight: '3.5 kg', babyDev: 'Your baby is ready to meet you! Their skull bones are not yet fused, allowing them to overlap during birth.', bodyChanges: 'You made it! Labor could start at any moment. Remember that due dates are just estimates.' }
];
