import React from 'react';
import {
  Footprints, Timer, Activity, Heart, Droplets,
  Apple, BookOpen, Users, Sparkles, Camera, Baby, Plane,
  Calendar, ShoppingBag, DollarSign, Clock, Syringe, FileText,
  Building, HeartHandshake, Briefcase, FileCheck2,
  HelpCircle, CheckCircle2, Wind, Pill, Map
} from 'lucide-react';

export interface ToolDefinition {
  id: string;
  title: string;
  desc: string;
  category: string;
  icon: React.ComponentType<{ size: number; className?: string; strokeWidth?: number }>;
  color: string;
  badge?: string;
  ritualSubtitle?: string;
  actionLabel?: string;
}

export const ALL_PREGNANCY_TOOLS: ToolDefinition[] = [
  // Category 1: Daily Tracking (9 tools)
  {
    id: 'hydration',
    title: 'Hydration Tracker',
    desc: 'Log water, tender coconut water & fluids',
    category: 'Daily Tracking',
    icon: Droplets,
    color: 'text-blue-600 bg-blue-50',
    badge: 'Daily',
    ritualSubtitle: 'Water & fluids goal',
    actionLabel: '+250ml Glass',
  },
  {
    id: 'nutrition',
    title: 'Supplements & Diet',
    desc: 'Folic acid, iron, calcium & daily vitamins',
    category: 'Daily Tracking',
    icon: Pill,
    color: 'text-emerald-700 bg-emerald-50',
    badge: 'Daily',
    ritualSubtitle: 'Folic, Iron, Calcium',
    actionLabel: '+ Mark Taken',
  },
  {
    id: 'kickcounter',
    title: 'Kick Counter',
    desc: 'Count 10 fetal kicks with active timer',
    category: 'Daily Tracking',
    icon: Footprints,
    color: 'text-sage-dark bg-sage-pale',
    badge: 'Active',
    ritualSubtitle: '10 kicks daily target',
    actionLabel: '+1 Kick',
  },
  {
    id: 'vitals',
    title: 'Vitals & BP Tracker',
    desc: 'Log blood pressure, pulse, weight & sugar',
    category: 'Daily Tracking',
    icon: Activity,
    color: 'text-rose-600 bg-rose-50',
    badge: 'Clinical',
    ritualSubtitle: 'Blood pressure & pulse',
    actionLabel: '+ Log Vitals',
  },
  {
    id: 'symptoms',
    title: 'Symptom Logger',
    desc: 'Track nausea, fatigue, swelling & cramps',
    category: 'Daily Tracking',
    icon: Heart,
    color: 'text-pink-600 bg-pink-50',
    badge: 'Daily',
    ritualSubtitle: 'Nausea, fatigue & swelling',
    actionLabel: '+ Log Symptoms',
  },
  {
    id: 'mood',
    title: 'Mood & Energy',
    desc: 'Daily emotional wellbeing & journal check-in',
    category: 'Daily Tracking',
    icon: Sparkles,
    color: 'text-amber-600 bg-amber-50',
    badge: 'Wellbeing',
    ritualSubtitle: 'Daily emotional check-in',
    actionLabel: '+ Check-in',
  },
  {
    id: 'notes',
    title: 'Bump Journal',
    desc: 'Private ultrasound notes & bump diary',
    category: 'Daily Tracking',
    icon: BookOpen,
    color: 'text-teal-700 bg-teal-50',
    ritualSubtitle: 'Ultrasound notes & diary',
    actionLabel: 'Write Note →',
  },
  {
    id: 'partnersync',
    title: 'Partner Sync (P2P)',
    desc: 'Encrypted WebRTC live companion sync',
    category: 'Daily Tracking',
    icon: Users,
    color: 'text-indigo-600 bg-indigo-50',
    badge: 'Sync',
    ritualSubtitle: 'Live companion connection',
    actionLabel: 'Sync Live →',
  },
  {
    id: 'contractions',
    title: 'Contraction Timer',
    desc: 'ACOG 5-1-1 labor contraction timer',
    category: 'Daily Tracking',
    icon: Timer,
    color: 'text-orange-600 bg-orange-50',
    badge: 'ACOG 5-1-1',
    ritualSubtitle: 'Labor contraction monitor',
    actionLabel: 'Start Timer →',
  },

  // Category 2: Smart AI & Cultural Guidance (5 tools)
  {
    id: 'askourpregnancy',
    title: 'Ask Bloom AI',
    desc: 'Empathetic OB-GYN clinical maternal chat',
    category: 'Smart AI & Guidance',
    icon: Sparkles,
    color: 'text-sage-dark bg-sage-pale',
    badge: 'FOGSI & ACOG',
    ritualSubtitle: 'Empathetic OB-GYN chat',
    actionLabel: 'Ask AI →',
  },
  {
    id: 'foodscanner',
    title: 'AI Food & Calorie Guide',
    desc: 'Meal calories, FOGSI vitamins, barcode & safety',
    category: 'Smart AI & Guidance',
    icon: Camera,
    color: 'text-sage-dark bg-sage-pale',
    badge: 'AI Vision',
    ritualSubtitle: 'Food safety & macros',
    actionLabel: 'Scan Meal →',
  },
  {
    id: 'breathing',
    title: 'Garbh Sanskar & Audio',
    desc: 'Guided breathing & offline prenatal audio',
    category: 'Smart AI & Guidance',
    icon: Wind,
    color: 'text-sage-dark bg-sage-pale',
    badge: 'Vedic',
    ritualSubtitle: 'Pranayama & soundscapes',
    actionLabel: 'Play Audio →',
  },
  {
    id: 'babynames',
    title: 'Baby Names Finder',
    desc: 'Indian modern & Vedic name meanings with rashi',
    category: 'Smart AI & Guidance',
    icon: Baby,
    color: 'text-pink-600 bg-pink-50',
    ritualSubtitle: 'Modern & Vedic meanings',
    actionLabel: 'Search Names →',
  },
  {
    id: 'travel',
    title: 'Safe Travel Guide',
    desc: 'Flying, road trips & doctor NOC guidelines',
    category: 'Smart AI & Guidance',
    icon: Plane,
    color: 'text-teal-600 bg-teal-50',
    ritualSubtitle: 'Flying & road guidelines',
    actionLabel: 'View Guide →',
  },
  {
    id: 'guide',
    title: 'How Our Pregnancy Works',
    desc: '5-step user journey, doctor setup & data privacy flow',
    category: 'Smart AI & Guidance',
    icon: Map,
    color: 'text-sage-dark bg-sage-pale',
    badge: 'Guide',
    ritualSubtitle: 'User flow & journey guide',
    actionLabel: 'View Flow →',
  },

  // Category 3: Planning & Milestones (4 tools)
  {
    id: 'dev',
    title: 'Fetal Development',
    desc: 'Week-by-week organogenesis timeline & size',
    category: 'Milestones & Prep',
    icon: Calendar,
    color: 'text-sage-dark bg-sage-pale',
    ritualSubtitle: 'Organogenesis timeline',
    actionLabel: 'View Timeline →',
  },
  {
    id: 'deadlines',
    title: 'Due Date Deadlines',
    desc: 'Essential prenatal scan milestones & visits',
    category: 'Milestones & Prep',
    icon: Clock,
    color: 'text-amber-700 bg-amber-50',
    ritualSubtitle: 'Scan schedule & visits',
    actionLabel: 'View Visits →',
  },
  {
    id: 'prep',
    title: 'Nursery & Baby Prep',
    desc: 'Essential checklists for baby gear & clothing',
    category: 'Milestones & Prep',
    icon: ShoppingBag,
    color: 'text-blue-600 bg-blue-50',
    ritualSubtitle: 'Checklists for baby gear',
    actionLabel: 'View Prep →',
  },
  {
    id: 'finance',
    title: 'Delivery Cost Planner',
    desc: 'Hospital delivery estimates, insurance & savings',
    category: 'Milestones & Prep',
    icon: DollarSign,
    color: 'text-emerald-700 bg-emerald-50',
    ritualSubtitle: 'Hospital cost calculator',
    actionLabel: 'Plan Budget →',
  },

  // Category 4: Medical & Schemes (4 tools)
  {
    id: 'schemes',
    title: 'Govt Maternity Schemes',
    desc: 'PMMVY (₹5k), JSY (₹1.4k), PMSMA & state aid',
    category: 'Medical & Schemes',
    icon: Building,
    color: 'text-yellow-700 bg-yellow-50',
    badge: 'MoHFW',
    ritualSubtitle: 'PMMVY & JSY benefits',
    actionLabel: 'View Schemes →',
  },
  {
    id: 'medical-reports',
    title: 'Medical Reports Locker',
    desc: 'Ultrasound scans & bloodwork AES-256 vault',
    category: 'Medical & Schemes',
    icon: FileText,
    color: 'text-cyan-700 bg-cyan-50',
    badge: 'ABHA',
    ritualSubtitle: 'AES-256 scan locker',
    actionLabel: 'Open Locker →',
  },
  {
    id: 'medical',
    title: 'Vaccines & Schedule',
    desc: 'Tdap, tetanus, glucose tolerance & labs',
    category: 'Medical & Schemes',
    icon: Syringe,
    color: 'text-rose-600 bg-rose-50',
    ritualSubtitle: 'Tdap, OGTT & vaccines',
    actionLabel: 'View Schedule →',
  },
  {
    id: 'postpartum',
    title: 'Postpartum Healing',
    desc: 'Fourth trimester recovery, pelvic floor & care',
    category: 'Medical & Schemes',
    icon: HeartHandshake,
    color: 'text-rose-600 bg-rose-50',
    ritualSubtitle: 'Fourth trimester care',
    actionLabel: 'Read Guide →',
  },

  // Category 5: Labor & Postpartum (4 tools)
  {
    id: 'hospitalbag',
    title: 'Hospital Bag Checklist',
    desc: 'Organized packing for mother, baby & partner',
    category: 'Labor & Postpartum',
    icon: Briefcase,
    color: 'text-stone-700 bg-stone-100',
    ritualSubtitle: 'Packing checklist',
    actionLabel: 'Pack Bag →',
  },
  {
    id: 'birthplan',
    title: 'Birth Plan Builder',
    desc: 'Preferences for labor, support person & pain relief',
    category: 'Labor & Postpartum',
    icon: FileCheck2,
    color: 'text-sage-dark bg-sage-pale',
    ritualSubtitle: 'Labor & delivery choices',
    actionLabel: 'Build Plan →',
  },
  {
    id: 'readiness',
    title: 'Labor Readiness Score',
    desc: 'Bishop score & cervical preparation guidance',
    category: 'Labor & Postpartum',
    icon: CheckCircle2,
    color: 'text-indigo-700 bg-indigo-50',
    ritualSubtitle: 'Bishop score guidance',
    actionLabel: 'Check Score →',
  },
  {
    id: 'feedback',
    title: 'Feedback & Support',
    desc: 'Share your pregnancy journey suggestions',
    category: 'Labor & Postpartum',
    icon: HelpCircle,
    color: 'text-charcoal bg-cream',
    ritualSubtitle: 'Help & feedback',
    actionLabel: 'Send Feedback →',
  },
];

export const CATEGORY_CHIPS = [
  { label: 'All', count: ALL_PREGNANCY_TOOLS.length, key: 'All' },
  { label: 'Daily Logs', count: 9, key: 'Daily Tracking' },
  { label: 'Smart AI', count: 5, key: 'Smart AI & Guidance' },
  { label: 'Milestones', count: 4, key: 'Milestones & Prep' },
  { label: 'Govt & Scans', count: 4, key: 'Medical & Schemes' },
  { label: 'Labor Prep', count: 4, key: 'Labor & Postpartum' },
];

export const getToolById = (id: string): ToolDefinition | undefined => {
  return ALL_PREGNANCY_TOOLS.find((t) => t.id === id);
};
